# Generated by Django 2.1.7 on 2019-04-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eddr',
            new_name='eaddr',
        ),
    ]
